### ISSUE TITLE
post_tweet with media

### ISSUE THREAD

**Issue by neuwirthe** [mkearney/rtweet#95]
I saw that not post_tweet has a media parameter.
But I could not make it work

I got an error when trying to post a tweet with an image,
but just posting a text only tweet immedately after that, things work.
So the error message seems to be misleading.

```
> post_tweet("d konrad test mit bild",media=tmp)
Error: Rate limit exceeded - please wait!
> post_tweet("d konrad test 3")
your tweet has been posted!
```

Can this be resolved?

**Comment by mkearney** [comment]
I'll try looking into this again. The [httr package makes it look easy](https://github.com/r-lib/httr/blob/master/R/upload-file.r) but last time I couldn't make it work with [Twitter's documentation on uploading media](https://dev.twitter.com/rest/reference/post/media/upload). The real problem is that I don't personally have a use for it---an unfortunate open source motivation problem :(.

**Comment by mkearney** [comment]
I think I figured it out @neuwirthe! It may only be limited to one media upload at a time for now, but assuming this works for you/others, it can probably easily be adjusted to allow for multiple image/media uploads.

**Comment by mkearney** [comment]
Closing this for now, but I'll reopen if any problems are reported with uploading media.

**Comment by neuwirthe** [comment]
I do not get the error any more, but the image is not posted/

**Comment by mkearney** [comment]
Sorry, I just realized I forgot to reorder function calls to validate token before uploading media. It's fixed now if you want to give it a try.

**Comment by neuwirthe** [comment]
I do not get the error messahe any more, but the media file mention in the media parameter does not get poseted.

**Comment by mkearney** [comment]
I overcorrected. I shouldn't have moved the query parameter, too. This is hopefully fixed now, but I won't be able to test it until this afternoon.

**Comment by neuwirthe** [comment]
It seems you introduced a new error :-(
> post_tweet("d konrad test with image 3",media="bacher.png")
Error in check_token(token, query) : object 'query' not found

**Comment by mkearney** [comment]
Oh of course I did! Just fixed it.

**Comment by neuwirthe** [comment]
Image still does not get send. You can use me as tester. just dens a direct message to neuwirthe
something like
`post_tweet("d neuwirthe tesst with image", media = "testimage.ng")`

**Comment by neuwirthe** [comment]
`post_tweet("d neuwirthe tesst with image", media = "testimage.png")`

**Comment by neuwirthe** [comment]
It still does not work, now a tweet like
`post_tweet("d konrad mit image",media="bacher.png")`
is sent without error, but the image is not really sent, it does not appear.
